// SETUP_ACTIONS
export const SET_SETUP_AND_LOADING = 'SET_SETUP_AND_LOADING'
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_PARAMETER = 'SET_PARAMETER'

// QUESTIONS_ACTIONS
export const SET_QUESTIONS = 'SET_QUESTIONS'
export const SET_ERROR = 'SET_ERROR'
export const NEXT_QUESTION = 'NEXT_QUESTION'

// COMMON_ACTIONS
export const CLOSE_MODAL = 'CLOSE_MODAL'
